### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lvZic** [maxrmorrison/pyfoal#10]
File "/home/vic/anaconda3/envs/text2audio/lib/python3.7/site-packages/pyfoal/core.py", line 174, in correct_alignment
    durations[0] += .0125
IndexError: list index out of range

just use the test.txt and test.wav, crashed as above.

**Comment by lvZic** [comment]
in correct_alignment.py line 168,  alignment = pypar.Alignment(alignment_file)
the returned alignment is of zero length, so i wonder if something wrong with HTK? 
I just install HTK and run HTK sample with successful result.

**Comment by maxrmorrison** [comment]
I'm not able to replicate your error on the test data. If the length of the duration vector is 0, that means HTK failed to perform an alignment. So something is wrong with your HTK installation. For example, maybe you installed 3.4.1 instead of 3.4.0.

**Comment by lvZic** [comment]
> I'm not able to replicate your error on the test data. If the length of the duration vector is 0, that means HTK failed to perform an alignment. So something is wrong with your HTK installation. For example, maybe you installed 3.4.1 instead of 3.4.0.

thanks for your reply and i have fixed HTK 3.4.1 by https://github.com/JoFrhwld/FAVE/wiki/HTK-3.4.1.
