### ISSUE TITLE
Alignment of Phonemes

### ISSUE THREAD

**Issue by SlistInc** [maxrmorrison/pyfoal#14]
I am using the Allosaurus library to extract phonemes from an audio file, since Allosaurus is able to work language indipendent. Is there a way to use pyfoal to align a list of phonemes rathert than a text? The language indipendence from such an approach would be very appreciated and open a plethora of possibilities.

**Comment by maxrmorrison** [comment]
The aligner models are trained in a language-specific fashion. So while two languages with the same phoneme set could technically use the same aligner, the aligner will work better on the language it was trained on. If you really want to try this yourself, Allosaurus is just a grapheme-to-phoneme (G2P) model. So you can swap out the English G2P model used in `pyfoal` with Allosaurus (see [this function](https://github.com/maxrmorrison/pyfoal/blob/1c82618c08a049aad3c02ae263999eb5775c40fd/pyfoal/core.py#L251)).

If you really want multilingual G2P + alignment, you might try Montreal Forced Aligner. In MFA, both the G2P and aligner can be retrained to a target language.
