### ISSUE TITLE
Possible to run this on AWS Lambda or Beam (beam.cloud)?

### ISSUE THREAD

**Issue by jimkleiber** [maxrmorrison/pyfoal#19]
I've been digging into Gentle a lot and having a lot of pain in setting it up locally and even on a remote server. I did finally set it up but have been trying to find a faster way to align the text/audio if possible. I recently learned about AWS Lambda functions, but also wondered 1) if it would be hard to adapt the Gentle code to use Lambda and 2) if it would even render that much faster than just using a remote server. Then I found https://beam.cloud that seems to do serverless but with GPUs and thought that might work for Gentle.

Then I stumbled on pyfoal.

It seems 1) it'll be easier to install in general, but 2) that it might align better with the serverless function models.

Have you thought about running it on AWS Lambda or Beam, and if not, do you think it might work?

**Comment by maxrmorrison** [comment]
I have found Gentle to be very useful for performing coarse alignments of long audio (i.e., fast, low-complexity), and the methods here for performing fine-grained alignment of short audio. For example, I used Gentle for chunking long audio into sentences followed by P2FA for fine-grained alignment. But I've only ever used P2FA and Gentle with CPU compute. So those should be fine with Lambda. I see of no reason why the GPU-based methods couldn't be hosted on either a CPU- or GPU-equivalent to Lambda. But, I have not tried this myself.
