### ISSUE TITLE
Remove torchaudio dependency from setup.py

### ISSUE THREAD

**Issue by naitian** [maxrmorrison/pyfoal#20]
Thanks for this package! I noticed that `torch` and `torchaudio` are no longer dependencies in #1 but they are still listed in the `setup.py`. In particular, the version pins make installing this package problematic, since I have torchaudio 2.2.0 installed. I ended up doing `pip install pyfoal --no-deps` and manually installing the other dependencies.

I'd be happy to make a PR if that'd make life easier for you.

**Comment by maxrmorrison** [comment]
Yes, I'd happily accept that PR.

**Comment by maxrmorrison** [comment]
@NathanPruyne ended up taking care of this to fix some functionality in a downstream project. Fixed in 9a106fcbe3bfa50852b76e3fb9e6d758dc8f9d3b and released in version 1.0.1.
