### ISSUE TITLE
any phoneme list?

### ISSUE THREAD

**Issue by lvZic** [maxrmorrison/pyfoal#9]
I wanna know where i can found the phoneme list that pyfoal used?

**Comment by lvZic** [comment]
i found the monophones file , and wonder if the monophones file can be modified by myself?

**Comment by maxrmorrison** [comment]
The phoneme list matches what is returned by HTK. You would have to start modifying HTK to change these phonemes. Or, you can write a wrapper that maps the phonemes to what you want them to be.

**Comment by lvZic** [comment]
> The phoneme list matches what is returned by HTK. You would have to start modifying HTK to change these phonemes. Or, you can write a wrapper that maps the phonemes to what you want them to be.

thanks for your reply. Because I donot need too much phonemes as in monophones file, I guess the returned aligning result consists of the phoneme list in monophones file. So the result would consists of  less monophones  while the phoneme list in monophones file is shortened a bit.
